esphome:
  name: activity-rings
  friendly_name: Activity Rings

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: homeassistant
    name: "Move"
    entity_id: input_number.michael_move_progress
    id: move_ha
  - platform: homeassistant
    name: "Stand"
    entity_id: input_number.michael_stand_progress
    id: stand_ha
  - platform: homeassistant
    name: "Exercise"
    entity_id: input_number.michael_exercise_progress
    id: exercise_ha
  - platform: homeassistant
    name: "Brightness"
    entity_id: input_number.activity_ring_brightness
    id: brightness_ha

light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO13
    num_leds: 171
    rgb_order: GRB
    id: ar_display
    name: "Display"

    on_turn_on:
      then:
        - light.control:
            id: ar_display
            effect: Calculate
            brightness: !lambda |-
              return id(brightness_ha).state;

    effects:
      - addressable_lambda:
          name: "Calculate"
          lambda: |-

            float move_percentage     = id(move_ha).state;
            float exercise_percentage = id(exercise_ha).state;
            float stand_percentage    = id(stand_ha).state;
            float brightness          = id(brightness_ha).state;

            int move_start = 0;
            int move_end   = 90;
            int exe_start  = 91;
            int exe_end    = 147;
            int stnd_start = 148;
            int stnd_end   = 171;

            int move_r  = 250 * brightness;
            int move_g  = 17 * brightness;
            int move_b  = 79 * brightness;
            int exe_r   = 166 * brightness;
            int exe_g   = 255 * brightness;
            int exe_b   = 0 * brightness;
            int stand_r = 0 * brightness;
            int stand_g = 255 * brightness;
            int stand_b = 246 * brightness;

            int move_leds  = move_end - move_start;
            int exe_leds   = exe_end - exe_start;
            int stnd_leds  = stnd_end - stnd_start;

            // Move
            if (isnan(move_percentage) || move_percentage < 2) {
              move_percentage = 2;
            }

            // The number of move leds to light up
            int m_leds = int(move_leds*move_percentage/100.0);
            int m_lit  = move_start + m_leds;

            // Set to the move color
            it.range(move_start, m_lit) = ESPColor(move_r,move_g,move_b);

            // Turn off the remaining leds
            if (m_lit+1 < move_end) {
              it.range(m_lit+1, move_end) = ESPColor::BLACK;
            }

            // Exercise 
            if (isnan(exercise_percentage) || exercise_percentage < 2) {
              exercise_percentage = 2;
            }

            // The number of exercise leds to light up
            int e_leds = int(exe_leds*exercise_percentage/100.0);
            int exe_lit = exe_start + e_leds;

            // Set to the exercise color
            it.range(exe_start, exe_lit) = ESPColor(exe_r,exe_g,exe_b);

            // Turn off the remaining leds
            if (exe_lit+1 < exe_end) {
              it.range(exe_lit+1, exe_end) = ESPColor::BLACK;
            }

            // Stand 
            if (isnan(stand_percentage) || stand_percentage < 5) {
              stand_percentage = 5;
            }

            // The number of stand leds to light up
            int s_leds = int(stnd_leds*stand_percentage/100.0);
            int s_lit  = stnd_start + s_leds;

            // Set to the stand color
            it.range(stnd_start, s_lit) = ESPColor(stand_r,stand_g,stand_b);

            // Turn off the remaining leds
            if (s_lit+1 < stnd_end) {
              it.range(s_lit+1, stnd_end) = ESPColor::BLACK;
            }
